---
title: "Financial impact of COVID-19 on professional mountaineers"
author: "Will Hardy"
date: "`r Sys.Date()`"
output: html_document
knit: (function(inputFile, encoding) { 
      out_dir <- '../reports';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, "summary_report.html")) })
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(lubridate)

knitr::opts_chunk$set(echo = FALSE)

survey_data <- 
  read_rds("../data/prof_mtnrs_covid_19_survey.rds")
  
# data by association
AMI <- survey_data %>% 
  filter(mem_ami == TRUE) %>% 
  mutate(association = "AMI")

BAIML <- survey_data %>% 
  filter(mem_baiml == TRUE) %>% 
  mutate(association = "BAIML")

BMG <- survey_data %>% 
  filter(mem_bmg == TRUE) %>% 
  mutate(association = "BMG")

MTA <- survey_data %>% 
  filter(mem_mta == TRUE) %>% 
  mutate(association = "MTA")

by_association <- bind_rows(AMI, BAIML, BMG, MTA) # cases will not be unique

```


# Survey respondants

## By sex

```{r}
survey_data %>% 
  group_by(sex) %>% 
  summarise(n = n(),
            mean_age = mean(age),
            sd_age = sd(age)) %>% 
  kable(digits = 1)
```


## By qualification

```{r}
survey_data %>% 
  select(starts_with("qual_")) %>% 
  summarise_all(sum) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  mutate(Qualification = as.factor(toupper(str_replace_all(rowname, "qual_", ""))),
         Count = V1) %>% 
  ggplot(aes(x = Qualification, y = Count, fill = Qualification)) +
  geom_col() +
  guides(fill = FALSE)
```


## By association

```{r}
survey_data %>% 
  select(starts_with("mem_")) %>% 
  summarise_all(sum) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  mutate(Association = as.factor(toupper(str_replace_all(rowname, "mem_", ""))),
         Count = V1) %>% 
  ggplot(aes(x = Association, y = Count, fill = Association)) +
  geom_col() +
  guides(fill = FALSE)
```


```{r association-membership}
by_association %>% 
  group_by(association, sex) %>% 
  summarise(n = n(),
            age = mean(age)) %>% 
  kable(caption = "Association demographics", digits = 1) %>% 
  kableExtra::group_rows(index = 1)
```


## By employment type

```{r}
survey_data %>% 
  group_by(`Employment status`) %>% 
  count() %>% 
  ggplot(aes(x = `Employment status`, y = n)) +
  geom_col()
```


# Summary

```{r}
survey_data %>% 
  filter(`Employment status` != "Owner") %>% # no persona income recorded
  group_by(`Employment status`) %>% 
  summarise(n = n(),
    `Mean income 18-19` = mean(total_income_18_19, na.rm = TRUE),
    `Median income 18-19` = median(total_income_18_19, na.rm = TRUE),
    `Mean expected income 20-21` = mean(total_exp_income, na.rm = TRUE),
    `Median expected income 20-21` = median(total_exp_income, na.rm = TRUE),
    `Mean exected loss` = mean(total_exp_losses, na.rm = TRUE),
    `Median exected loss` = median(total_exp_losses, na.rm = TRUE),) %>% 
  kable(digits = 0)
```


## Self-employed

```{r self-employed-income-18-19, fig.cap="Distribution of self-employed income for 2018-2019 tax year. Only showing data for those who reported self-employed earnings for 2018-2019"}
survey_data %>% 
  filter(self_income_18_19 > 0) %>% 
  ggplot(aes(x = self_income_18_19)) +
  geom_histogram(binwidth = 5000) + 
  xlab("Income (£)")
```


## Employee

```{r}
survey_data %>% 
  ggplot(aes(x = sex, y = employee_income_18_19)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0, 50000))
```


## Total personal

```{r}
survey_data %>% 
  ggplot(aes(x = sex, y = total_income_18_19)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0, 50000))
```


# Expected losses

```{r}
survey_data %>% 
  select(ends_with("exp_losses")) %>% 
  summarise_all(sum, na.rm = TRUE) %>% 
  kable(caption = "Total expected losses 2018-2019",
        col.names = c("Self-employed", "Employee", "Buisness", "Total personal"))

survey_data %>% 
  select(ends_with("exp_losses")) %>% 
  summarise_all(median, na.rm = TRUE) %>% 
  kable(caption = "Median expected losses 2018-2019",
        col.names = c("Self-employed", "Employee", "Buisness", "Total personal"))

survey_data %>% 
  filter(alternate_career == FALSE) %>% 
  select(ends_with("exp_losses")) %>% 
  summarise_all(median, na.rm = TRUE) %>% 
  kable(caption = "Median expected losses 2018-2019 for those with no alternate career",
        col.names = c("Self-employed", "Employee", "Buisness", "Total personal"))

```


## By association

```{r, warning=FALSE}
by_association %>% 
  group_by(association) %>% 
  summarise(`Mean loss of earnings` = mean(total_exp_losses, na.rm = TRUE),
            `Mean loss of earnings as % of 18-19 income` = 
              100*mean(total_exp_losses, na.rm = TRUE)/
              mean(total_income_18_19, na.rm = TRUE)) %>% 
  kable(digits = 1, caption = "Loss of earnings by association")
```



